"""update vehicule Model

Revision ID: 00709be17d41
Revises: 243190f893ee
Create Date: 2025-02-23 19:36:15.072459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00709be17d41'
down_revision = '243190f893ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_de_vehicule', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('type_de_carburant', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('localisation', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('puissance', sa.String(length=15), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('puissance')
        batch_op.drop_column('localisation')
        batch_op.drop_column('type_de_carburant')
        batch_op.drop_column('type_de_vehicule')

    # ### end Alembic commands ###
