"""cascade set up

Revision ID: 09fc1788ff8a
Revises: e2beaa966292
Create Date: 2025-02-04 09:17:37.541562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fc1788ff8a'
down_revision = 'e2beaa966292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_constraint('incident_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('incident_reservation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.drop_constraint('insurance_reservation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_constraint('password_reset_code_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payment_reservation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('reservation_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reservation_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('review_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('support_request', schema=None) as batch_op:
        batch_op.drop_constraint('support_request_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.drop_constraint('user_image_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('vehicle_image', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_image_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vehicle_image_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vehicle_owner_id_fkey', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_image_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('support_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('support_request_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('review_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservation_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('reservation_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_reservation_id_fkey', 'reservation', ['reservation_id'], ['id'])
        batch_op.create_foreign_key('payment_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('password_reset_code_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('insurance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('insurance_reservation_id_fkey', 'reservation', ['reservation_id'], ['id'])

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('incident_reservation_id_fkey', 'reservation', ['reservation_id'], ['id'])
        batch_op.create_foreign_key('incident_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
