"""user and userImage update

Revision ID: 0c0228e0e0e4
Revises: a015ef010490
Create Date: 2025-01-29 16:19:59.046554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0228e0e0e4'
down_revision = 'a015ef010490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Prenom', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nom', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(None, ['telephone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('telephone')
        batch_op.drop_column('nom')
        batch_op.drop_column('Prenom')

    op.drop_table('user_image')
    # ### end Alembic commands ###
