"""add siege in model vehicule

Revision ID: 1b16a7da9417
Revises: cadc18e9237f
Create Date: 2025-03-02 14:58:21.503632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b16a7da9417'
down_revision = 'cadc18e9237f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nbreSieges', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('nbreSieges')

    # ### end Alembic commands ###
