"""update vehiculeImages Model

Revision ID: 243190f893ee
Revises: 09fc1788ff8a
Create Date: 2025-02-23 17:38:50.520423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243190f893ee'
down_revision = '09fc1788ff8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_image', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['file_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###
