"""user update

Revision ID: 461a1ec38648
Revises: 0c0228e0e0e4
Create Date: 2025-01-29 18:33:37.554464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461a1ec38648'
down_revision = '0c0228e0e0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom', sa.String(length=120), nullable=True))
        batch_op.drop_column('Prenom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Prenom', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('prenom')

    # ### end Alembic commands ###
