"""Revoved token models

Revision ID: 74280decf44d
Revises: 926a3e41379d
Create Date: 2025-02-03 09:09:05.171296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74280decf44d'
down_revision = '926a3e41379d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token')
    # ### end Alembic commands ###
