"""Ajout du champ is_active pour activation

Revision ID: 926a3e41379d
Revises: fefc8f237511
Create Date: 2025-01-31 09:10:53.417139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926a3e41379d'
down_revision = 'fefc8f237511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
