"""add transmission and vitesse in model

Revision ID: cadc18e9237f
Revises: 00709be17d41
Create Date: 2025-03-02 14:54:47.563109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadc18e9237f'
down_revision = '00709be17d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transmission', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vitesse', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('vitesse')
        batch_op.drop_column('transmission')

    # ### end Alembic commands ###
